server:
  port: 0

eureka:
   instance:
      prefer-ip-address: true
   client:
      serviceUrl:
       defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.spring.product
spring:  
    datasource:
      url: jdbc:mysql://localhost:3306/product
      username: root
      password: root
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          ddl-auto: update
      show-sql: true
  